### ISSUE TITLE
Congradulation with release...

### ISSUE THREAD

**Issue by githubbla** [gelijergensen/PermutationImportance#8]
could you please provide samples on how to use it?

thanks in advance.

**Comment by gelijergensen** [comment]
I just merged in some changes to the README for example usage and also some explanation on the optional parameters to the function. You can also find a complete example in the bottom of the variable_importances.py file

If something doesn't make sense or you have a particular example you would like, let me know and I'll see if I can add it

**Comment by gelijergensen** [comment]
Closing after 1 month of inactivity

**Comment by gelijergensen** [comment]
@githubbla I recently made a breaking update to the code. The permutation_selection_importance function now returns an object which has bundled the ranks and importances in a more natural way. Please see the README and permutation_importance/importance_result.py for the object definition. If you should for any reason need the old return value, you can simply use `result.complete_result`, which I have left for legacy purposes. However, I will note that the new `get_variable_importances_and_scores` and `get_variable_ranks_and_scores` will probably be more useful. Cheers!
