### ISSUE TITLE
Predictions and targets are out of order in sklearn_api.py

### ISSUE THREAD

**Issue by monte-flora** [gelijergensen/PermutationImportance#80]
In the sklearn_api.py on line 139:
`return self.evaluation_fn(predictions, scoring_outputs, **self.kwargs`
and on line 149-150: 
`scores.append(self.evaluation_fn(
                    subsampled_predictions, subsampled_scoring_outputs, **self.kwargs))`
The predictions and scoring_outputs are in the wrong order. The scoring_outputs should come first.

**Comment by gelijergensen** [comment]
Sure enough, good catch! PR #81 will fix that and I'll push the corrected version up to PIP in a few minutes.

**Comment by monte-flora** [comment]
No problem.

**Comment by gelijergensen** [comment]
Alright, the corrected version is up on PyPI. You should be able to simply do `pip install -U PermutationImportance` and everything should be fixed
